### ISSUE TITLE
Please add license to repo

### ISSUE THREAD

**Issue by Reinachan** [Rouji/single_php_filehost_docker#4]
Hi! I'd like to use a modified version of your dockerfile in my own implementation of this project. Can you add a license to this repo so that I can properly attribute you? I've currently added a comment at the top based on the license in the main repo, but using anything from unlicensed projects is a legal no-go-zone so I'd prefer if this had an explicit license :p

**Comment by Rouji** [comment]
I'm guessing you mean [this](https://github.com/Reinachan/filehost/blob/master/Filehost/Dockerfile)?
IANAL, but I think you're not really allowed to do basically anything with my code unless a license says otherwise(?) I personally don't really mind, but just saying I don't think that comment at the top is correct. Could be wrong though.
I'll probably give it the same license as the filehost repo. But might be a few hours til I get home and do that. 


(also slightly surprised anyone would build off of this instead of just throwing together a custom Dockerfile 🙃)

**Comment by Reinachan** [comment]
> I'm guessing you mean [this](https://github.com/Reinachan/filehost/blob/master/Filehost/Dockerfile?rgh-link-date=2022-10-25T07%3A51%3A09Z)?

Yeah, sorry, kinda forgot that I should've waited until after this got a license before hitting publish :p

> ANAL, but I think you're not really allowed to do basically anything with my code unless a license says otherwise

I think you're right about that, and I wouldn't have if it wasn't for how this repo is basically an extension to that other repo. License laws are really annoying tbh. I just made the filehosting setup as a personal project and wanted to let others use it. Licensing laws really only practically apply to big corpos that have the money to uphold them. If you decided to not add a license or put a different or incompatible one in here, wanted me to take it down, or just didn't respond in time, I'd figure out a different way to do stuff.

> I don't think that comment at the top is correct

Afaik, it's correct going by the assumption that this project would be licensed the same as the parent repo, which is what I did before I forgot and published it.

> (also slightly surprised anyone would build off of this instead of just throwing together a custom Dockerfile upside_down_face)

I'd do a custom dockerfile if it wasn't for my lack of experience with PHP tbh. If I can figure out how, I'll probably have Caddy handle the PHP instead of Nginx, in which case I'll write my own dockerfile. Ideally I'd also figure out the permission stuff so I can more easily manually delete files from the host machine (currently have to `sudo rm`). But for now, modifying your dockerfile made the most sense to me :p

**Comment by Rouji** [comment]
8215d4dbd07e457cfff709da3a363357b1e4cd66 should do the trick. And yeah, now the comment does tell the truth 😃
Licensing stuff is annoying indeed. But necessary because some people are bellends, unfortunately.

As for the `sudo rm`, there's probably some `docker exec something something rm` thing you can do. I should probably make the uid/gid configurable, but am lazy 🤷

**Comment by Reinachan** [comment]
For sure. I've started licensing my stuff with AGPLv3 recently so that big corpos can't use my code in their projects. It also enforces anyone else using my code to leave a strong copyleft license on their projects, which I think is nice.

Ideally all code would just be FOSS and it was just common practice to credit people for their work rather than needing copyrights :/ 

But it is what it is.

You can close this issue now I suppose then. Thanks :)

**Comment by Rouji** [comment]
Alright, closing this then 👍  

GPL and friends are a good choice, but I feel it's a bit overkill for hacky scripty stuff like this 🙃
